#
# @lc app=leetcode id=389 lang=python
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (52.72%)
# Total Accepted:    139.8K
# Total Submissions: 264.5K
# Testcase Example:  '"abcd"\n"abcde"'
#
# 
# Given two strings s and t which consist of only lowercase letters.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Find the letter that was added in t.
# 
# Example:
# 
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
# 
#
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        return chr(reduce(lambda x,y: x ^ y, map(ord, list(s+t))))

    def _findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        # wrong understand
        # i = 0
        # j = 0
        # while j < len(t):
        #     if i >= len(s):
        #         return t[j]
        #     if s[i] == t[j]:
        #         i += 1
        #         j += 1
        #     else:
        #         return t[j]

        s = list(s)
        for i in t:
            if i in s:
                s.remove(i)
            else:
                return i
